[package]
name = "bevy_cheap_fluids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.60"

[dependencies.bevy]
version = "0.12"
default-features = false
features = [
    "dynamic_linking",
    "multi-threaded"
]